#!/bin/bash
set -e

case "$1" in
configure)
	# initialization
	add_env_key=("COGL_DRIVER" "GSK_RENDERER" "GSK_GPU_DISABLE" "GDK_GL" "SDL_VIDEODRIVER" "SAL_DISABLEGL" "SAL_ENABLESKIA")
	add_env_value=("gles2" "gl" "mipmap" "gles" "wayland" "1" "1")
	add_num=${#add_env_key[@]}

	remove_env_key=()
	remove_num=${#remove_env_key[@]}

	# remove environment key in /etc/environment
	for ((i=0; i<$remove_num; i++))
	do
        	echo "Delete all the ${remove_env_key[${i}]} lines in /etc/environment"
        	sed -i "/${remove_env_key[${i}]}/d" /etc/environment
	done

	# add new environment key to /etc/environment
	for ((i=0; i<$add_num; i++))
	do
        	line=`cat /etc/environment | grep ${add_env_key[${i}]} | tail -1`
        	old_key=${line%=*}
        	old_value=${line#*=}
        	if [ "${add_env_value[${i}]}" != "${old_value}" ];then
                	echo "Add ${add_env_key[${i}]}=${add_env_value[${i}]} to /etc/environment"
                	echo "${add_env_key[${i}]}=${add_env_value[${i}]}" >>/etc/environment
        	fi
	done
    ;;
esac
exit 0
