#include "cl_img_external_semaphore.h"

#ifndef __OPENCL_CL_IMG_EXTERNAL_SEMAPHORE_SYNC_FD_H
#define __OPENCL_CL_IMG_EXTERNAL_SEMAPHORE_SYNC_FD_H

#define CL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_IMG		(1<<3)

#endif /*__OPENCL_CL_IMG_EXTERNAL_SEMAPHORE_SYNC_FD_H*/
